// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzMswDhuc2Oi_jLNkOboIeKRMC0H72Ggw',
    appId: '1:826651027450:web:a4a24ac42e78100d902643',
    messagingSenderId: '826651027450',
    projectId: 'megu-firebase-auth',
    authDomain: 'megu-firebase-auth.firebaseapp.com',
    storageBucket: 'megu-firebase-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYLDbS48TVig21TzzPUkBAQgSKuclmRYs',
    appId: '1:826651027450:android:edc9e6e69cf873c7902643',
    messagingSenderId: '826651027450',
    projectId: 'megu-firebase-auth',
    storageBucket: 'megu-firebase-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf9-6KVHdWJ5eoIjqcW9IqRsfVd7AvgJs',
    appId: '1:826651027450:ios:d3e797fd66a5661e902643',
    messagingSenderId: '826651027450',
    projectId: 'megu-firebase-auth',
    storageBucket: 'megu-firebase-auth.appspot.com',
    iosClientId: '826651027450-77cs7be5b5m10a1qj3m5r70ctet5bcm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWord',
  );
}
